<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Producto;
use App\Models\Categoria;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        // Obtener categorías
        $iphone = Categoria::where('slug', 'iphone')->first();
        $samsung = Categoria::where('slug', 'samsung')->first();
        $laptops = Categoria::where('slug', 'laptops')->first();
        $refrigeradoras = Categoria::where('slug', 'refrigeradoras')->first();
        $lavadoras = Categoria::where('slug', 'lavadoras')->first();

        // Productos iPhone
        if ($iphone) {
            // iPhone 11 Series
            Producto::create([
                'nombre' => 'iPhone 11 64GB',
                'slug' => 'iphone-11-64gb',
                'descripcion' => 'iPhone 11 con chip A13 Bionic y cámara dual. Pantalla Liquid Retina de 6.1 pulgadas.',
                'precio' => 2299.00,
                'precio_oferta' => 2099.00,
                'stock' => 35,
                'sku' => 'IPH11-64001',
                'codigo_barras' => '194253098701',
                'imagen_principal' => 'assets/productos/iphone-11-64g.png',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 11',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 11 64GB - Doble cámara',
                'meta_description' => 'iPhone 11 con chip A13 Bionic y sistema de doble cámara',
                'atributos_extra' => json_encode([
                    'chip' => 'A13 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'almacenamiento' => '64GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 11 128GB',
                'slug' => 'iphone-11-128gb',
                'descripcion' => 'iPhone 11 con chip A13 Bionic y cámara dual. Pantalla Liquid Retina de 6.1 pulgadas - 128GB.',
                'precio' => 2499.00,
                'precio_oferta' => 2299.00,
                'stock' => 40,
                'sku' => 'IPH11-128001',
                'codigo_barras' => '194253098702',
                'imagen_principal' => 'assets/productos/iphone-11-128g.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 11',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 11 128GB - Más almacenamiento',
                'meta_description' => 'iPhone 11 con 128GB de almacenamiento y doble cámara',
                'atributos_extra' => json_encode([
                    'chip' => 'A13 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 11 Pro Max 64GB',
                'slug' => 'iphone-11-pro-max-64gb',
                'descripcion' => 'iPhone 11 Pro Max con pantalla Super Retina XDR de 6.5 pulgadas y triple cámara.',
                'precio' => 3999.00,
                'precio_oferta' => 3699.00,
                'stock' => 20,
                'sku' => 'IPH11PM-64001',
                'codigo_barras' => '194253098703',
                'imagen_principal' => 'assets/productos/iphone-11-PM-64g.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 11 Pro Max',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 11 Pro Max 64GB - Triple cámara Pro',
                'meta_description' => 'iPhone 11 Pro Max con sistema de triple cámara profesional',
                'atributos_extra' => json_encode([
                    'chip' => 'A13 Bionic',
                    'camara' => 'Triple cámara Pro 12MP',
                    'almacenamiento' => '64GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 11 Pro Max 256GB',
                'slug' => 'iphone-11-pro-max-256gb',
                'descripcion' => 'iPhone 11 Pro Max con pantalla Super Retina XDR de 6.5 pulgadas y triple cámara - 256GB.',
                'precio' => 4399.00,
                'precio_oferta' => 4099.00,
                'stock' => 15,
                'sku' => 'IPH11PM-256001',
                'codigo_barras' => '194253098704',
                'imagen_principal' => 'assets/productos/iphone-11-PM-256g.png',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 11 Pro Max',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 11 Pro Max 256GB - Máximo almacenamiento',
                'meta_description' => 'iPhone 11 Pro Max con 256GB y sistema de triple cámara Pro',
                'atributos_extra' => json_encode([
                    'chip' => 'A13 Bionic',
                    'camara' => 'Triple cámara Pro 12MP',
                    'almacenamiento' => '256GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 11 Pro 64GB',
                'slug' => 'iphone-11-pro-64gb',
                'descripcion' => 'iPhone 11 Pro con pantalla Super Retina XDR de 5.8 pulgadas y triple cámara.',
                'precio' => 3799.00,
                'precio_oferta' => 3499.00,
                'stock' => 25,
                'sku' => 'IPH11P-64001',
                'codigo_barras' => '194253098705',
                'imagen_principal' => 'assets/productos/iphone-11-PRO-64g.png',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 11 Pro',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 11 Pro 64GB - Cámara profesional',
                'meta_description' => 'iPhone 11 Pro con sistema de triple cámara y pantalla Pro',
                'atributos_extra' => json_encode([
                    'chip' => 'A13 Bionic',
                    'camara' => 'Triple cámara Pro 12MP',
                    'almacenamiento' => '64GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 11 Pro 256GB',
                'slug' => 'iphone-11-pro-256gb',
                'descripcion' => 'iPhone 11 Pro con pantalla Super Retina XDR de 5.8 pulgadas y triple cámara - 256GB.',
                'precio' => 4199.00,
                'precio_oferta' => 3899.00,
                'stock' => 18,
                'sku' => 'IPH11P-256001',
                'codigo_barras' => '194253098706',
                'imagen_principal' => 'assets/productos/iphone-11-PRO-256g.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 11 Pro',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 11 Pro 256GB - Pro con más espacio',
                'meta_description' => 'iPhone 11 Pro con 256GB y sistema de triple cámara profesional',
                'atributos_extra' => json_encode([
                    'chip' => 'A13 Bionic',
                    'camara' => 'Triple cámara Pro 12MP',
                    'almacenamiento' => '256GB',
                ]),
            ]);

            // iPhone 12 Series
            Producto::create([
                'nombre' => 'iPhone 12 64GB',
                'slug' => 'iphone-12-64gb',
                'descripcion' => 'iPhone 12 con chip A14 Bionic y conectividad 5G. Pantalla Super Retina XDR de 6.1 pulgadas.',
                'precio' => 2999.00,
                'precio_oferta' => 2799.00,
                'stock' => 30,
                'sku' => 'IPH12-64001',
                'codigo_barras' => '194253098707',
                'imagen_principal' => 'assets/productos/iphone-12-64g.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 12',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 12 64GB - 5G y A14 Bionic',
                'meta_description' => 'iPhone 12 con conectividad 5G y chip A14 Bionic',
                'atributos_extra' => json_encode([
                    'chip' => 'A14 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'conectividad' => '5G',
                    'almacenamiento' => '64GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 12 128GB',
                'slug' => 'iphone-12-128gb',
                'descripcion' => 'iPhone 12 con chip A14 Bionic y conectividad 5G. Pantalla Super Retina XDR de 6.1 pulgadas - 128GB.',
                'precio' => 3199.00,
                'precio_oferta' => 2999.00,
                'stock' => 35,
                'sku' => 'IPH12-128001',
                'codigo_barras' => '194253098708',
                'imagen_principal' => 'assets/productos/iphone-12-128g.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 12',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 12 128GB - Más espacio y 5G',
                'meta_description' => 'iPhone 12 con 128GB, 5G y chip A14 Bionic',
                'atributos_extra' => json_encode([
                    'chip' => 'A14 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'conectividad' => '5G',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 12 Pro Mini 64GB',
                'slug' => 'iphone-12-pro-mini-64gb',
                'descripcion' => 'iPhone 12 Pro Mini compacto con todas las características Pro en tamaño reducido.',
                'precio' => 3299.00,
                'precio_oferta' => 3099.00,
                'stock' => 20,
                'sku' => 'IPH12PM-64001',
                'codigo_barras' => '194253098709',
                'imagen_principal' => 'assets/productos/iphone-12-PRO-256g.png',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 12 Pro Mini',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 12 Pro Mini 64GB - Pro compacto',
                'meta_description' => 'iPhone 12 Pro Mini con características Pro en tamaño pequeño',
                'atributos_extra' => json_encode([
                    'chip' => 'A14 Bionic',
                    'camara' => 'Triple cámara Pro 12MP',
                    'tamaño' => 'Compacto Pro',
                    'almacenamiento' => '64GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 12 Mini 128GB',
                'slug' => 'iphone-12-mini-128gb',
                'descripcion' => 'iPhone 12 Mini compacto con chip A14 Bionic. Pantalla de 5.4 pulgadas - 128GB.',
                'precio' => 2899.00,
                'precio_oferta' => 2699.00,
                'stock' => 25,
                'sku' => 'IPH12M-128001',
                'codigo_barras' => '194253098710',
                'imagen_principal' => 'assets/productos/iphone-12-mini-128g.png',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 12 Mini',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 12 Mini 128GB - Compacto y potente',
                'meta_description' => 'iPhone 12 Mini con 128GB en tamaño compacto',
                'atributos_extra' => json_encode([
                    'chip' => 'A14 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'tamaño' => 'Compacto 5.4"',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 12 Pro Max 256GB',
                'slug' => 'iphone-12-pro-max-256gb',
                'descripcion' => 'iPhone 12 Pro Max con pantalla de 6.7 pulgadas y sistema de triple cámara Pro.',
                'precio' => 4599.00,
                'precio_oferta' => 4299.00,
                'stock' => 15,
                'sku' => 'IPH12PM256-001',
                'codigo_barras' => '194253098711',
                'imagen_principal' => 'assets/productos/iphone-12-PM-256-gb.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 12 Pro Max',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 12 Pro Max 256GB - El más grande',
                'meta_description' => 'iPhone 12 Pro Max con pantalla de 6.7" y 256GB',
                'atributos_extra' => json_encode([
                    'chip' => 'A14 Bionic',
                    'camara' => 'Triple cámara Pro 12MP',
                    'pantalla' => '6.7" Pro Max',
                    'almacenamiento' => '256GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 12 Pro 128GB',
                'slug' => 'iphone-12-pro-128gb',
                'descripcion' => 'iPhone 12 Pro con sistema de triple cámara Pro y pantalla Super Retina XDR.',
                'precio' => 3999.00,
                'precio_oferta' => 3699.00,
                'stock' => 22,
                'sku' => 'IPH12P-128001',
                'codigo_barras' => '194253098712',
                'imagen_principal' => 'assets/productos/iphone-12-pro-128g.png',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 12 Pro',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 12 Pro 128GB - Cámara profesional',
                'meta_description' => 'iPhone 12 Pro con triple cámara y 128GB de almacenamiento',
                'atributos_extra' => json_encode([
                    'chip' => 'A14 Bionic',
                    'camara' => 'Triple cámara Pro 12MP',
                    'video' => 'ProRes y Dolby Vision',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            // iPhone 13 Series
            Producto::create([
                'nombre' => 'iPhone 13 128GB',
                'slug' => 'iphone-13-128gb',
                'descripcion' => 'iPhone 13 con chip A15 Bionic y cámara dual mejorada. Pantalla Super Retina XDR de 6.1 pulgadas.',
                'precio' => 3199.00,
                'precio_oferta' => 2999.00,
                'stock' => 40,
                'sku' => 'IPH13-128001',
                'codigo_barras' => '194253098713',
                'imagen_principal' => 'assets/productos/iphone-13-128gb.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 13',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 13 128GB - A15 Bionic',
                'meta_description' => 'iPhone 13 con chip A15 Bionic y cámara dual avanzada',
                'atributos_extra' => json_encode([
                    'chip' => 'A15 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'bateria' => 'Hasta 19 horas de video',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 13 256GB',
                'slug' => 'iphone-13-256gb',
                'descripcion' => 'iPhone 13 con chip A15 Bionic y cámara dual mejorada - 256GB de almacenamiento.',
                'precio' => 3599.00,
                'precio_oferta' => 3299.00,
                'stock' => 35,
                'sku' => 'IPH13-256001',
                'codigo_barras' => '194253098714',
                'imagen_principal' => 'assets/productos/iphone-13-256gb.png',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 13',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 13 256GB - Más almacenamiento',
                'meta_description' => 'iPhone 13 con 256GB y chip A15 Bionic avanzado',
                'atributos_extra' => json_encode([
                    'chip' => 'A15 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'bateria' => 'Hasta 19 horas de video',
                    'almacenamiento' => '256GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 13 Mini 64GB',
                'slug' => 'iphone-13-mini-64gb',
                'descripcion' => 'iPhone 13 Mini compacto con chip A15 Bionic. Pantalla de 5.4 pulgadas.',
                'precio' => 2799.00,
                'precio_oferta' => 2599.00,
                'stock' => 28,
                'sku' => 'IPH13M-64001',
                'codigo_barras' => '194253098715',
                'imagen_principal' => 'assets/productos/iphone-13-mini-64g.png',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 13 Mini',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 13 Mini 64GB - Pequeño y potente',
                'meta_description' => 'iPhone 13 Mini con A15 Bionic en tamaño compacto',
                'atributos_extra' => json_encode([
                    'chip' => 'A15 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'tamaño' => 'Compacto 5.4"',
                    'almacenamiento' => '64GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 13 Mini 128GB',
                'slug' => 'iphone-13-mini-128gb',
                'descripcion' => 'iPhone 13 Mini compacto con chip A15 Bionic - 128GB de almacenamiento.',
                'precio' => 2999.00,
                'precio_oferta' => 2799.00,
                'stock' => 30,
                'sku' => 'IPH13M-128001',
                'codigo_barras' => '194253098716',
                'imagen_principal' => 'assets/productos/iphone-13-mini-128-gb.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 13 Mini',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 13 Mini 128GB - Compacto ideal',
                'meta_description' => 'iPhone 13 Mini con 128GB y rendimiento A15 Bionic',
                'atributos_extra' => json_encode([
                    'chip' => 'A15 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'tamaño' => 'Compacto 5.4"',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 13 Pro Max 128GB',
                'slug' => 'iphone-13-pro-max-128gb',
                'descripcion' => 'iPhone 13 Pro Max con pantalla ProMotion de 6.7 pulgadas y sistema de triple cámara Pro.',
                'precio' => 4399.00,
                'precio_oferta' => 4099.00,
                'stock' => 18,
                'sku' => 'IPH13PM-128001',
                'codigo_barras' => '194253098717',
                'imagen_principal' => 'assets/productos/iphone-13-PM-128g.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 13 Pro Max',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 13 Pro Max 128GB - ProMotion',
                'meta_description' => 'iPhone 13 Pro Max con pantalla ProMotion y cámaras Pro',
                'atributos_extra' => json_encode([
                    'chip' => 'A15 Bionic',
                    'camara' => 'Triple cámara Pro 12MP',
                    'pantalla' => 'ProMotion 120Hz 6.7"',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 13 Pro Max 256GB',
                'slug' => 'iphone-13-pro-max-256gb',
                'descripcion' => 'iPhone 13 Pro Max con pantalla ProMotion de 6.7 pulgadas - 256GB de almacenamiento.',
                'precio' => 4799.00,
                'precio_oferta' => 4499.00,
                'stock' => 15,
                'sku' => 'IPH13PM-256001',
                'codigo_barras' => '194253098718',
                'imagen_principal' => 'assets/productos/iphone-13-PM-256g.png',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 13 Pro Max',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 13 Pro Max 256GB - Máximo rendimiento',
                'meta_description' => 'iPhone 13 Pro Max con 256GB y características Pro avanzadas',
                'atributos_extra' => json_encode([
                    'chip' => 'A15 Bionic',
                    'camara' => 'Triple cámara Pro 12MP',
                    'pantalla' => 'ProMotion 120Hz 6.7"',
                    'almacenamiento' => '256GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 13 Pro 128GB',
                'slug' => 'iphone-13-pro-128gb',
                'descripcion' => 'iPhone 13 Pro con sistema de cámaras Pro, pantalla ProMotion y chip A15 Bionic.',
                'precio' => 3999.00,
                'precio_oferta' => 3699.00,
                'stock' => 25,
                'sku' => 'IPH13P-128001',
                'codigo_barras' => '194253098719',
                'imagen_principal' => 'assets/productos/iphone-13-pro-128g.png',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 13 Pro',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 13 Pro 128GB - Sistema Pro',
                'meta_description' => 'iPhone 13 Pro con cámaras Pro y pantalla ProMotion',
                'atributos_extra' => json_encode([
                    'chip' => 'A15 Bionic',
                    'camara' => 'Triple cámara Pro 12MP',
                    'pantalla' => 'ProMotion 120Hz',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 13 Pro 256GB',
                'slug' => 'iphone-13-pro-256gb',
                'descripcion' => 'iPhone 13 Pro con sistema de cámaras Pro, pantalla ProMotion - 256GB de almacenamiento.',
                'precio' => 4399.00,
                'precio_oferta' => 4099.00,
                'stock' => 20,
                'sku' => 'IPH13P-256001',
                'codigo_barras' => '194253098720',
                'imagen_principal' => 'assets/productos/iphone-13-pro-256g.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 13 Pro',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 13 Pro 256GB - Pro con más espacio',
                'meta_description' => 'iPhone 13 Pro con 256GB y sistema de cámaras profesional',
                'atributos_extra' => json_encode([
                    'chip' => 'A15 Bionic',
                    'camara' => 'Triple cámara Pro 12MP',
                    'pantalla' => 'ProMotion 120Hz',
                    'almacenamiento' => '256GB',
                ]),
            ]);

            // iPhone 14 Series
            Producto::create([
                'nombre' => 'iPhone 14 128GB',
                'slug' => 'iphone-14-128gb',
                'descripcion' => 'iPhone 14 con chip A15 Bionic y cámara mejorada. Pantalla Super Retina XDR de 6.1 pulgadas.',
                'precio' => 3299.00,
                'precio_oferta' => 2999.00,
                'stock' => 40,
                'sku' => 'IPH14-128001',
                'codigo_barras' => '194253098721',
                'imagen_principal' => 'assets/productos/iphone-14-128g.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 14',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 14 128GB - Tecnología avanzada',
                'meta_description' => 'iPhone 14 con chip A15 Bionic y sistema de cámaras avanzado',
                'atributos_extra' => json_encode([
                    'chip' => 'A15 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'bateria' => 'Hasta 20 horas de video',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 14 256GB',
                'slug' => 'iphone-14-256gb',
                'descripcion' => 'iPhone 14 con chip A15 Bionic y cámara mejorada - 256GB de almacenamiento.',
                'precio' => 3699.00,
                'precio_oferta' => 3399.00,
                'stock' => 32,
                'sku' => 'IPH14-256001',
                'codigo_barras' => '194253098722',
                'imagen_principal' => 'assets/productos/iphone-14-256g.png',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 14',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 14 256GB - Más capacidad',
                'meta_description' => 'iPhone 14 con 256GB y características avanzadas',
                'atributos_extra' => json_encode([
                    'chip' => 'A15 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'bateria' => 'Hasta 20 horas de video',
                    'almacenamiento' => '256GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 14 Plus 128GB',
                'slug' => 'iphone-14-plus-128gb',
                'descripcion' => 'iPhone 14 Plus con pantalla más grande de 6.7 pulgadas y mayor duración de batería.',
                'precio' => 3799.00,
                'precio_oferta' => 3499.00,
                'stock' => 28,
                'sku' => 'IPH14P-128001',
                'codigo_barras' => '194253098723',
                'imagen_principal' => 'assets/productos/iphone-14-plus-128-g.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 14 Plus',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 14 Plus 128GB - Pantalla grande',
                'meta_description' => 'iPhone 14 Plus con pantalla de 6.7" y batería de larga duración',
                'atributos_extra' => json_encode([
                    'chip' => 'A15 Bionic',
                    'camara' => '12MP Principal + 12MP Ultra Angular',
                    'pantalla' => '6.7" Super Retina XDR',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'iPhone 14 Pro Max 128GB',
                'slug' => 'iphone-14-pro-max-128gb',
                'descripcion' => 'iPhone 14 Pro Max con Dynamic Island, chip A16 Bionic y cámara principal de 48MP.',
                'precio' => 4999.00,
                'precio_oferta' => 4699.00,
                'stock' => 20,
                'sku' => 'IPH14PM-128001',
                'codigo_barras' => '194253098724',
                'imagen_principal' => 'assets/productos/iphone-14-plus-128-g.png',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $iphone->id,
                'marca' => 'Apple',
                'modelo' => 'iPhone 14 Pro Max',
                'garantia' => '1 año',
                'meta_title' => 'iPhone 14 Pro Max 128GB - Dynamic Island',
                'meta_description' => 'iPhone 14 Pro Max con Dynamic Island y cámara de 48MP',
                'atributos_extra' => json_encode([
                    'chip' => 'A16 Bionic',
                    'camara' => '48MP Principal + 12MP Ultra Angular + 12MP Telefoto',
                    'dynamic_island' => 'Sí',
                    'almacenamiento' => '128GB',
                ]),
            ]);
        }

        // Productos Samsung
        if ($samsung) {
            // Galaxy S23 Series
            Producto::create([
                'nombre' => 'Samsung Galaxy S23 FE 8GB + 128GB',
                'slug' => 'samsung-galaxy-s23-fe-8gb-128gb',
                'descripcion' => 'Galaxy S23 FE con pantalla Dynamic AMOLED de 6.4 pulgadas, 8GB de RAM y 128GB de almacenamiento.',
                'precio' => 1899.00,
                'precio_oferta' => 1699.00,
                'stock' => 45,
                'sku' => 'SGS23FE-128001',
                'codigo_barras' => '887276543210',
                'imagen_principal' => 'assets/productos/S23-FE-8-128G.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $samsung->id,
                'marca' => 'Samsung',
                'modelo' => 'Galaxy S23 FE',
                'garantia' => '1 año',
                'meta_title' => 'Samsung Galaxy S23 FE 8GB+128GB - Calidad y precio',
                'meta_description' => 'Galaxy S23 FE con 8GB RAM, 128GB almacenamiento y fotografía profesional',
                'atributos_extra' => json_encode([
                    'procesador' => 'Exynos 2200',
                    'camara' => '50MP Principal + 12MP Ultra Angular + 8MP Telefoto',
                    'ram' => '8GB',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Samsung Galaxy S23 Plus 256GB',
                'slug' => 'samsung-galaxy-s23-plus-256gb',
                'descripcion' => 'Galaxy S23+ con pantalla de 6.6 pulgadas, rendimiento flagship y 256GB de almacenamiento.',
                'precio' => 3499.00,
                'precio_oferta' => 3199.00,
                'stock' => 25,
                'sku' => 'SGS23P-256001',
                'codigo_barras' => '887276543211',
                'imagen_principal' => 'assets/productos/SAMSUNG-S23-PLUS-256G.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $samsung->id,
                'marca' => 'Samsung',
                'modelo' => 'Galaxy S23+',
                'garantia' => '1 año',
                'meta_title' => 'Samsung Galaxy S23+ 256GB - Rendimiento premium',
                'meta_description' => 'Galaxy S23+ con 256GB y rendimiento excepcional',
                'atributos_extra' => json_encode([
                    'procesador' => 'Snapdragon 8 Gen 2',
                    'camara' => '50MP Principal + 12MP Ultra Angular + 10MP Telefoto',
                    'pantalla' => '6.6" Dynamic AMOLED 2X',
                    'almacenamiento' => '256GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Samsung Galaxy S23 Plus 512GB',
                'slug' => 'samsung-galaxy-s23-plus-512gb',
                'descripcion' => 'Galaxy S23+ con pantalla de 6.6 pulgadas, rendimiento flagship y 512GB de almacenamiento.',
                'precio' => 3899.00,
                'precio_oferta' => 3599.00,
                'stock' => 20,
                'sku' => 'SGS23P-512001',
                'codigo_barras' => '887276543213',
                'imagen_principal' => 'assets/productos/SAMSUNG-S23-PLUS-512G.jpg',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $samsung->id,
                'marca' => 'Samsung',
                'modelo' => 'Galaxy S23+',
                'garantia' => '1 año',
                'meta_title' => 'Samsung Galaxy S23+ 512GB - Máximo almacenamiento',
                'meta_description' => 'Galaxy S23+ con 512GB para usuarios exigentes',
                'atributos_extra' => json_encode([
                    'procesador' => 'Snapdragon 8 Gen 2',
                    'camara' => '50MP Principal + 12MP Ultra Angular + 10MP Telefoto',
                    'pantalla' => '6.6" Dynamic AMOLED 2X',
                    'almacenamiento' => '512GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Samsung Galaxy S23 Ultra 256GB',
                'slug' => 'samsung-galaxy-s23-ultra-256gb',
                'descripcion' => 'Galaxy S23 Ultra con S Pen integrado, cámara de 200MP y pantalla de 6.8 pulgadas - 256GB.',
                'precio' => 4299.00,
                'precio_oferta' => 3999.00,
                'stock' => 30,
                'sku' => 'SGS23U-256001',
                'codigo_barras' => '887276543214',
                'imagen_principal' => 'assets/productos/S23-ULTRA-256G.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $samsung->id,
                'marca' => 'Samsung',
                'modelo' => 'Galaxy S23 Ultra',
                'garantia' => '1 año',
                'meta_title' => 'Samsung Galaxy S23 Ultra 256GB - S Pen incluido',
                'meta_description' => 'Galaxy S23 Ultra con S Pen, cámara de 200MP y 256GB',
                'atributos_extra' => json_encode([
                    'procesador' => 'Snapdragon 8 Gen 2',
                    'camara' => '200MP Principal + 50MP Telefoto + 12MP Ultra Angular',
                    's_pen' => 'Incluido',
                    'almacenamiento' => '256GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Samsung Galaxy S23 Ultra 512GB',
                'slug' => 'samsung-galaxy-s23-ultra-512gb',
                'descripcion' => 'Galaxy S23 Ultra con S Pen integrado, cámara de 200MP y pantalla de 6.8 pulgadas - 512GB.',
                'precio' => 4799.00,
                'precio_oferta' => 4499.00,
                'stock' => 25,
                'sku' => 'SGS23U-512001',
                'codigo_barras' => '887276543215',
                'imagen_principal' => 'assets/productos/S23-ULTRA-512G.jpg',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $samsung->id,
                'marca' => 'Samsung',
                'modelo' => 'Galaxy S23 Ultra',
                'garantia' => '1 año',
                'meta_title' => 'Samsung Galaxy S23 Ultra 512GB - Máxima capacidad',
                'meta_description' => 'Galaxy S23 Ultra con S Pen, cámara de 200MP y 512GB',
                'atributos_extra' => json_encode([
                    'procesador' => 'Snapdragon 8 Gen 2',
                    'camara' => '200MP Principal + 50MP Telefoto + 12MP Ultra Angular',
                    's_pen' => 'Incluido',
                    'almacenamiento' => '512GB',
                ]),
            ]);

            // Galaxy S24 Series
            Producto::create([
                'nombre' => 'Samsung Galaxy S24 128GB',
                'slug' => 'samsung-galaxy-s24-128gb',
                'descripcion' => 'Galaxy S24 con chip Snapdragon 8 Gen 3, pantalla Dynamic AMOLED 2X de 6.2 pulgadas y 128GB.',
                'precio' => 2899.00,
                'precio_oferta' => 2699.00,
                'stock' => 40,
                'sku' => 'SGS24-128001',
                'codigo_barras' => '887276543216',
                'imagen_principal' => 'assets/productos/S24-128G.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $samsung->id,
                'marca' => 'Samsung',
                'modelo' => 'Galaxy S24',
                'garantia' => '1 año',
                'meta_title' => 'Samsung Galaxy S24 128GB - Nueva generación',
                'meta_description' => 'Galaxy S24 con Snapdragon 8 Gen 3 y 128GB de almacenamiento',
                'atributos_extra' => json_encode([
                    'procesador' => 'Snapdragon 8 Gen 3',
                    'camara' => '50MP Principal + 12MP Ultra Angular + 10MP Telefoto',
                    'pantalla' => '6.2" Dynamic AMOLED 2X',
                    'almacenamiento' => '128GB',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Samsung Galaxy S24 256GB',
                'slug' => 'samsung-galaxy-s24-256gb',
                'descripcion' => 'Galaxy S24 con chip Snapdragon 8 Gen 3, pantalla Dynamic AMOLED 2X de 6.2 pulgadas y 256GB.',
                'precio' => 3199.00,
                'precio_oferta' => 2999.00,
                'stock' => 35,
                'sku' => 'SGS24-256001',
                'codigo_barras' => '887276543217',
                'imagen_principal' => 'assets/productos/S24-256G.jpg',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $samsung->id,
                'marca' => 'Samsung',
                'modelo' => 'Galaxy S24',
                'garantia' => '1 año',
                'meta_title' => 'Samsung Galaxy S24 256GB - Más almacenamiento',
                'meta_description' => 'Galaxy S24 con Snapdragon 8 Gen 3 y 256GB de almacenamiento',
                'atributos_extra' => json_encode([
                    'procesador' => 'Snapdragon 8 Gen 3',
                    'camara' => '50MP Principal + 12MP Ultra Angular + 10MP Telefoto',
                    'pantalla' => '6.2" Dynamic AMOLED 2X',
                    'almacenamiento' => '256GB',
                ]),
            ]);

            

            Producto::create([
                'nombre' => 'Samsung Galaxy S24 Ultra 256GB',
                'slug' => 'samsung-galaxy-s24-ultra-256gb',
                'descripcion' => 'El Galaxy más potente con S Pen integrado, cámara de 200MP y pantalla Dynamic AMOLED 2X de 6.8 pulgadas.',
                'precio' => 4799.00,
                'precio_oferta' => 4499.00,
                'stock' => 30,
                'sku' => 'SGS24U-256001',
                'codigo_barras' => '887276543219',
                'imagen_principal' => 'assets/productos/S24-ULTRA-256G.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $samsung->id,
                'marca' => 'Samsung',
                'modelo' => 'Galaxy S24 Ultra',
                'garantia' => '1 año',
                'meta_title' => 'Samsung Galaxy S24 Ultra 256GB - Productividad extrema',
                'meta_description' => 'Galaxy S24 Ultra con S Pen, cámara de 200MP y rendimiento excepcional',
                'atributos_extra' => json_encode([
                    'procesador' => 'Snapdragon 8 Gen 3',
                    'camara' => '200MP Principal + 50MP Telefoto + 12MP Ultra Angular',
                    's_pen' => 'Incluido',
                    'almacenamiento' => '256GB',
                ]),
            ]);

            // Galaxy Z Series (Plegables)
            Producto::create([
                'nombre' => 'Samsung Galaxy Z Fold4 256GB',
                'slug' => 'samsung-galaxy-z-fold4-256gb',
                'descripcion' => 'Galaxy Z Fold4 plegable con pantalla principal de 7.6 pulgadas, multitarea avanzada y 256GB.',
                'precio' => 6999.00,
                'precio_oferta' => 6499.00,
                'stock' => 15,
                'sku' => 'SGZF4-256001',
                'codigo_barras' => '887276543220',
                'imagen_principal' => 'assets/productos/FOLD-4-256G.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $samsung->id,
                'marca' => 'Samsung',
                'modelo' => 'Galaxy Z Fold4',
                'garantia' => '1 año',
                'meta_title' => 'Samsung Galaxy Z Fold4 256GB - Smartphone plegable',
                'meta_description' => 'Galaxy Z Fold4 con pantalla plegable, productividad extrema y 256GB',
                'atributos_extra' => json_encode([
                    'procesador' => 'Snapdragon 8+ Gen 1',
                    'pantalla_principal' => '7.6" Dynamic AMOLED 2X',
                    'pantalla_exterior' => '6.2" Dynamic AMOLED 2X',
                    'almacenamiento' => '256GB',
                    'tipo' => 'Plegable',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Samsung Galaxy Z Flip4 256GB',
                'slug' => 'samsung-galaxy-z-flip4-256gb',
                'descripcion' => 'Galaxy Z Flip4 plegable compacto con pantalla de 6.7 pulgadas y diseño icónico.',
                'precio' => 4299.00,
                'precio_oferta' => 3999.00,
                'stock' => 20,
                'sku' => 'SGZF4C-256001',
                'codigo_barras' => '887276543221',
                'imagen_principal' => 'assets/productos/Z-FLIP4-256G.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $samsung->id,
                'marca' => 'Samsung',
                'modelo' => 'Galaxy Z Flip4',
                'garantia' => '1 año',
                'meta_title' => 'Samsung Galaxy Z Flip4 256GB - Plegable compacto',
                'meta_description' => 'Galaxy Z Flip4 con diseño plegable compacto y 256GB de almacenamiento',
                'atributos_extra' => json_encode([
                    'procesador' => 'Snapdragon 8+ Gen 1',
                    'pantalla_principal' => '6.7" Dynamic AMOLED 2X',
                    'pantalla_exterior' => '1.9" Super AMOLED',
                    'almacenamiento' => '256GB',
                    'tipo' => 'Plegable compacto',
                ]),
            ]);
        }

        // Productos Laptops
        if ($laptops) {
            // Dell Latitude Series

            Producto::create([
                'nombre' => 'Dell Latitude 3420 Core i5',
                'slug' => 'dell-latitude-3420-core-i5',
                'descripcion' => 'Laptop empresarial Dell Latitude 3420 con procesador Intel Core i5, ideal para productividad.',
                'precio' => 2899.00,
                'precio_oferta' => 2699.00,
                'stock' => 20,
                'sku' => 'DL3420I5-001',
                'codigo_barras' => '884116864321',
                'imagen_principal' => 'assets/productos/DELL-LATITUDE-3420-CORE-I5.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $laptops->id,
                'marca' => 'Dell',
                'modelo' => 'Latitude 3420',
                'garantia' => '1 año',
                'meta_title' => 'Dell Latitude 3420 Core i5 - Rendimiento profesional',
                'meta_description' => 'Laptop Dell Latitude 3420 con Core i5 para trabajo profesional',
                'atributos_extra' => json_encode([
                    'procesador' => 'Intel Core i5',
                    'pantalla' => '14" Full HD',
                    'ram' => '8GB DDR4',
                    'almacenamiento' => '256GB SSD',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Dell Latitude 3510 Core i5',
                'slug' => 'dell-latitude-3510-core-i5',
                'descripcion' => 'Laptop empresarial Dell Latitude 3510 con pantalla de 15.6 pulgadas y procesador Intel Core i5.',
                'precio' => 3199.00,
                'precio_oferta' => 2999.00,
                'stock' => 18,
                'sku' => 'DL3510I5-001',
                'codigo_barras' => '884116864322',
                'imagen_principal' => 'assets/productos/DELL-LATITUDE-3510-CORE-I5.jpg',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $laptops->id,
                'marca' => 'Dell',
                'modelo' => 'Latitude 3510',
                'garantia' => '1 año',
                'meta_title' => 'Dell Latitude 3510 Core i5 - Pantalla grande',
                'meta_description' => 'Laptop Dell Latitude 3510 con pantalla de 15.6" y Core i5',
                'atributos_extra' => json_encode([
                    'procesador' => 'Intel Core i5',
                    'pantalla' => '15.6" Full HD',
                    'ram' => '8GB DDR4',
                    'almacenamiento' => '256GB SSD',
                ]),
            ]);

            // Lenovo Education Series
            Producto::create([
                'nombre' => 'Lenovo 300e 2nd Gen Pentium Silver',
                'slug' => 'lenovo-300e-2nd-gen-pentium-silver',
                'descripcion' => 'Laptop convertible Lenovo 300e de 2da generación con procesador Pentium Silver, ideal para educación.',
                'precio' => 1299.00,
                'precio_oferta' => 1199.00,
                'stock' => 35,
                'sku' => 'L300E2G-001',
                'codigo_barras' => '889488765430',
                'imagen_principal' => 'assets/productos/LENOVO-300E-2ND-GEN-PENTIUM-SILVER.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $laptops->id,
                'marca' => 'Lenovo',
                'modelo' => '300e 2nd Gen',
                'garantia' => '1 año',
                'meta_title' => 'Lenovo 300e 2nd Gen - Convertible para educación',
                'meta_description' => 'Laptop convertible Lenovo 300e con Pentium Silver para estudiantes',
                'atributos_extra' => json_encode([
                    'procesador' => 'Intel Pentium Silver',
                    'pantalla' => '11.6" HD Táctil',
                    'ram' => '4GB DDR4',
                    'tipo' => 'Convertible 360°',
                ]),
            ]);

            // Lenovo ThinkPad Series
            Producto::create([
                'nombre' => 'Lenovo ThinkPad T480',
                'slug' => 'lenovo-thinkpad-t480',
                'descripcion' => 'ThinkPad T480 con excelente teclado, durabilidad empresarial y rendimiento confiable.',
                'precio' => 2999.00,
                'precio_oferta' => 2799.00,
                'stock' => 22,
                'sku' => 'LT480-001',
                'codigo_barras' => '889488765431',
                'imagen_principal' => 'assets/productos/lenovo-thinkpad-T480.jpg',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $laptops->id,
                'marca' => 'Lenovo',
                'modelo' => 'ThinkPad T480',
                'garantia' => '1 año',
                'meta_title' => 'Lenovo ThinkPad T480 - Confiabilidad empresarial',
                'meta_description' => 'ThinkPad T480 con teclado premium y durabilidad empresarial',
                'atributos_extra' => json_encode([
                    'procesador' => 'Intel Core i5/i7',
                    'pantalla' => '14" Full HD',
                    'teclado' => 'ThinkPad premium',
                    'durabilidad' => 'Estándar militar',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Lenovo ThinkPad T490s',
                'slug' => 'lenovo-thinkpad-t490s',
                'descripcion' => 'ThinkPad T490s ultraligero con excelente teclado y rendimiento empresarial de alta gama.',
                'precio' => 3499.00,
                'precio_oferta' => 3199.00,
                'stock' => 15,
                'sku' => 'LT490S-001',
                'codigo_barras' => '889488765432',
                'imagen_principal' => 'assets/productos/LENOVO-THINKPAD-T490S.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $laptops->id,
                'marca' => 'Lenovo',
                'modelo' => 'ThinkPad T490s',
                'garantia' => '1 año',
                'meta_title' => 'Lenovo ThinkPad T490s - Ultraligero y potente',
                'meta_description' => 'ThinkPad T490s con diseño ultraligero y rendimiento profesional',
                'atributos_extra' => json_encode([
                    'procesador' => 'Intel Core i7',
                    'peso' => '1.27 kg',
                    'pantalla' => '14" Full HD',
                    'teclado' => 'ThinkPad premium',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Lenovo ThinkPad X13 Gen 1 Ryzen 7 Pro',
                'slug' => 'lenovo-thinkpad-x13-gen1-ryzen7-pro',
                'descripcion' => 'ThinkPad X13 compacto con procesador AMD Ryzen 7 Pro y excelente portabilidad.',
                'precio' => 3799.00,
                'precio_oferta' => 3499.00,
                'stock' => 12,
                'sku' => 'LX13R7-001',
                'codigo_barras' => '889488567890',
                'imagen_principal' => 'assets/productos/LENOVO-THINKPAD-X13-Gen-1-RYZEN-7-PRO.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $laptops->id,
                'marca' => 'Lenovo',
                'modelo' => 'ThinkPad X13 Gen 1',
                'garantia' => '1 año',
                'meta_title' => 'Lenovo ThinkPad X13 Ryzen 7 Pro - Compacto y potente',
                'meta_description' => 'ThinkPad X13 con AMD Ryzen 7 Pro y máxima portabilidad',
                'atributos_extra' => json_encode([
                    'procesador' => 'AMD Ryzen 7 Pro',
                    'pantalla' => '13.3" Full HD',
                    'seguridad' => 'TPM 2.0',
                    'peso' => '1.29 kg',
                ]),
            ]);
        }

        // Productos Refrigeradoras
        if ($refrigeradoras) {
            // Frigobar Serie
            Producto::create([
                'nombre' => 'Frigobar Indurama RI-159 Blanco',
                'slug' => 'frigobar-indurama-ri-159-blanco',
                'descripcion' => 'Frigobar Indurama RI-159 de 159 litros en color blanco, compacto y eficiente para espacios pequeños.',
                'precio' => 699.00,
                'precio_oferta' => 629.00,
                'stock' => 30,
                'sku' => 'IND-RI159B-001',
                'codigo_barras' => '884116123450',
                'imagen_principal' => 'assets/productos/FRIGOBAR-INDURAMA-FRIGOBAR-RI-159-BLANCO.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $refrigeradoras->id,
                'marca' => 'Indurama',
                'modelo' => 'RI-159',
                'garantia' => '2 años',
                'meta_title' => 'Frigobar Indurama RI-159 Blanco - Compacto',
                'meta_description' => 'Frigobar Indurama RI-159 de 159L ideal para espacios pequeños',
                'atributos_extra' => json_encode([
                    'capacidad' => '159 litros',
                    'tipo' => 'Frigobar',
                    'color' => 'Blanco',
                    'eficiencia' => 'Clase A',
                ]),
            ]);

            // Refrigeradoras Serie RI-200
            Producto::create([
                'nombre' => 'Refrigeradora Indurama RI-289DBI',
                'slug' => 'refrigeradora-indurama-ri-289dbi',
                'descripcion' => 'Refrigeradora Indurama de 289 litros con dispensador de agua y tecnología No Frost.',
                'precio' => 1899.00,
                'precio_oferta' => 1699.00,
                'stock' => 25,
                'sku' => 'IND-RI289DBI-001',
                'codigo_barras' => '884116123451',
                'imagen_principal' => 'assets/productos/REFRIGERADORA-INDURAMA-REFRIGERADORA-RI-289DBL.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $refrigeradoras->id,
                'marca' => 'Indurama',
                'modelo' => 'RI-289DBI',
                'garantia' => '2 años',
                'meta_title' => 'Refrigeradora Indurama RI-289DBI - No Frost con dispensador',
                'meta_description' => 'Refrigeradora Indurama 289L con dispensador y tecnología No Frost',
                'atributos_extra' => json_encode([
                    'capacidad' => '289 litros',
                    'tecnologia' => 'No Frost',
                    'dispensador' => 'Agua externa',
                    'eficiencia' => 'Clase A+',
                ]),
            ]);

            

            // Refrigeradoras Serie RI-300
            Producto::create([
                'nombre' => 'Refrigeradora Indurama RI-389DN',
                'slug' => 'refrigeradora-indurama-ri-389dn',
                'descripcion' => 'Refrigeradora Indurama RI-389DN de 389 litros con tecnología No Frost y gran capacidad.',
                'precio' => 2299.00,
                'precio_oferta' => 2099.00,
                'stock' => 20,
                'sku' => 'IND-RI389DN-001',
                'codigo_barras' => '884116123453',
                'imagen_principal' => 'assets/productos/REFRIGERADORA-INDURAMA-REFRIGERADORA-RI-389DNI.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $refrigeradoras->id,
                'marca' => 'Indurama',
                'modelo' => 'RI-389DN',
                'garantia' => '2 años',
                'meta_title' => 'Refrigeradora Indurama RI-389DN - Gran capacidad No Frost',
                'meta_description' => 'Refrigeradora Indurama 389L con tecnología No Frost avanzada',
                'atributos_extra' => json_encode([
                    'capacidad' => '389 litros',
                    'tecnologia' => 'No Frost',
                    'tipo' => 'Dúplex',
                    'eficiencia' => 'Clase A+',
                ]),
            ]);

            // Refrigeradoras Serie RI-400
            Producto::create([
                'nombre' => 'Refrigeradora Indurama RI-469DI',
                'slug' => 'refrigeradora-indurama-ri-469di',
                'descripcion' => 'Refrigeradora Indurama RI-469DI de 469 litros con dispensador interno y amplio espacio.',
                'precio' => 2599.00,
                'precio_oferta' => 2399.00,
                'stock' => 18,
                'sku' => 'IND-RI469DI-001',
                'codigo_barras' => '884116123454',
                'imagen_principal' => 'assets/productos/REFRIGERADORA-INDURAMA-REFRIGERADORA-RI-469DI.jpg',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $refrigeradoras->id,
                'marca' => 'Indurama',
                'modelo' => 'RI-469DI',
                'garantia' => '2 años',
                'meta_title' => 'Refrigeradora Indurama RI-469DI - 469L con dispensador',
                'meta_description' => 'Refrigeradora Indurama 469L con dispensador interno y gran capacidad',
                'atributos_extra' => json_encode([
                    'capacidad' => '469 litros',
                    'dispensador' => 'Interno',
                    'tipo' => 'Side by Side',
                    'eficiencia' => 'Clase A+',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Refrigeradora Indurama RI-478DN',
                'slug' => 'refrigeradora-indurama-ri-478dn',
                'descripcion' => 'Refrigeradora Indurama RI-478DN de 478 litros con tecnología No Frost y diseño moderno.',
                'precio' => 2699.00,
                'precio_oferta' => 2499.00,
                'stock' => 16,
                'sku' => 'IND-RI478DN-001',
                'codigo_barras' => '884116123455',
                'imagen_principal' => 'assets/productos/REFRIGERADORA-INDURAMA-REFRIGERADORA-RI-478DN.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $refrigeradoras->id,
                'marca' => 'Indurama',
                'modelo' => 'RI-478DN',
                'garantia' => '2 años',
                'meta_title' => 'Refrigeradora Indurama RI-478DN - 478L No Frost',
                'meta_description' => 'Refrigeradora Indurama 478L con tecnología No Frost y diseño moderno',
                'atributos_extra' => json_encode([
                    'capacidad' => '478 litros',
                    'tecnologia' => 'No Frost',
                    'tipo' => 'Side by Side',
                    'eficiencia' => 'Clase A+',
                ]),
            ]);

            // Refrigeradoras Serie RI-500
            Producto::create([
                'nombre' => 'Refrigeradora Indurama RI-529DI',
                'slug' => 'refrigeradora-indurama-ri-529di',
                'descripcion' => 'Refrigeradora Indurama RI-529DI de 529 litros con dispensador interno, ideal para familias grandes.',
                'precio' => 2999.00,
                'precio_oferta' => 2799.00,
                'stock' => 14,
                'sku' => 'IND-RI529DI-001',
                'codigo_barras' => '884116123456',
                'imagen_principal' => 'assets/productos/REFRIGERADORA-INDURAMA-REFRIGERADORA-RI-529DI.jpg',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $refrigeradoras->id,
                'marca' => 'Indurama',
                'modelo' => 'RI-529DI',
                'garantia' => '2 años',
                'meta_title' => 'Refrigeradora Indurama RI-529DI - 529L máxima capacidad',
                'meta_description' => 'Refrigeradora Indurama 529L con dispensador interno para familias grandes',
                'atributos_extra' => json_encode([
                    'capacidad' => '529 litros',
                    'dispensador' => 'Interno',
                    'tipo' => 'Side by Side',
                    'eficiencia' => 'Clase A++',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Refrigeradora Indurama RI-578DN',
                'slug' => 'refrigeradora-indurama-ri-578dn',
                'descripcion' => 'Refrigeradora Indurama RI-578DN de 578 litros, el modelo de mayor capacidad con tecnología No Frost.',
                'precio' => 3299.00,
                'precio_oferta' => 2999.00,
                'stock' => 12,
                'sku' => 'IND-RI578DN-001',
                'codigo_barras' => '884116123457',
                'imagen_principal' => 'assets/productos/REFRIGERADORA-INDURAMA-REFRIGERADORA-RI-578DN.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $refrigeradoras->id,
                'marca' => 'Indurama',
                'modelo' => 'RI-578DN',
                'garantia' => '2 años',
                'meta_title' => 'Refrigeradora Indurama RI-578DN - 578L máxima capacidad',
                'meta_description' => 'Refrigeradora Indurama 578L, el modelo de mayor capacidad con No Frost',
                'atributos_extra' => json_encode([
                    'capacidad' => '578 litros',
                    'tecnologia' => 'No Frost',
                    'tipo' => 'Side by Side',
                    'eficiencia' => 'Clase A++',
                ]),
            ]);
        }

        // Productos Lavadoras
        if ($lavadoras) {
            // Lavadoras Indurama Serie Compacta
            Producto::create([
                'nombre' => 'Lavadora Indurama Automática LRI-11DGR 11 KG',
                'slug' => 'lavadora-indurama-automatica-lri-11dgr-11kg',
                'descripcion' => 'Lavadora Indurama automática de 11 kg de capacidad, ideal para hogares medianos con eficiencia energética.',
                'precio' => 899.00,
                'precio_oferta' => 799.00,
                'stock' => 35,
                'sku' => 'IND-LRI11DGR-001',
                'codigo_barras' => '884116987650',
                'imagen_principal' => 'assets/productos/LAVADORA-INDURAMA-LAVADORA-AUTOMATICA-LRI-11DGR.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $lavadoras->id,
                'marca' => 'Indurama',
                'modelo' => 'LRI-11DGR',
                'garantia' => '2 años',
                'meta_title' => 'Lavadora Indurama LRI-11DGR 11KG - Compacta y eficiente',
                'meta_description' => 'Lavadora Indurama automática de 11 kg con ahorro de agua y energía',
                'atributos_extra' => json_encode([
                    'capacidad' => '11 kg',
                    'tipo' => 'Carga superior',
                    'programas' => '8 programas de lavado',
                    'eficiencia' => 'Ahorro energético',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Lavadora Indurama Automática LRI-13BLA 13 KG',
                'slug' => 'lavadora-indurama-automatica-lri-13bla-13kg',
                'descripcion' => 'Lavadora Indurama automática de 13 kg en color blanco, perfecta para familias medianas.',
                'precio' => 1099.00,
                'precio_oferta' => 999.00,
                'stock' => 32,
                'sku' => 'IND-LRI13BLA-001',
                'codigo_barras' => '884116987651',
                'imagen_principal' => 'assets/productos/LAVADORA-INDURAMA-LAVADORA-AUTOMATICA-LRI-13BLA.jpg',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $lavadoras->id,
                'marca' => 'Indurama',
                'modelo' => 'LRI-13BLA',
                'garantia' => '2 años',
                'meta_title' => 'Lavadora Indurama LRI-13BLA 13KG - Blanco elegante',
                'meta_description' => 'Lavadora Indurama 13 kg en blanco con tecnología automática',
                'atributos_extra' => json_encode([
                    'capacidad' => '13 kg',
                    'tipo' => 'Carga superior',
                    'color' => 'Blanco',
                    'programas' => '10 programas de lavado',
                ]),
            ]);

            // Lavadoras Indurama Serie Media
           

            Producto::create([
                'nombre' => 'Lavadora Indurama Automática LRI-16DGR 16 KG',
                'slug' => 'lavadora-indurama-automatica-lri-16dgr-16kg',
                'descripcion' => 'Lavadora Indurama automática de 16 kg con diseño moderno y alta eficiencia en el lavado.',
                'precio' => 1299.00,
                'precio_oferta' => 1199.00,
                'stock' => 30,
                'sku' => 'IND-LRI16DGR-001',
                'codigo_barras' => '884116987653',
                'imagen_principal' => 'assets/productos/LAVADORA-INDURAMA-LAVADORA-AUTOMATICA-LRI-16DGR.jpg',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $lavadoras->id,
                'marca' => 'Indurama',
                'modelo' => 'LRI-16DGR',
                'garantia' => '2 años',
                'meta_title' => 'Lavadora Indurama LRI-16DGR 16KG - Alta eficiencia',
                'meta_description' => 'Lavadora Indurama 16 kg con diseño moderno y lavado eficiente',
                'atributos_extra' => json_encode([
                    'capacidad' => '16 kg',
                    'tipo' => 'Carga superior',
                    'programas' => '12 programas de lavado',
                    'eficiencia' => 'Alta eficiencia',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Lavadora Indurama Automática LRI-16DTN 16 KG',
                'slug' => 'lavadora-indurama-automatica-lri-16dtn-16kg',
                'descripcion' => 'Lavadora Indurama automática de 16 kg con control digital y múltiples programas de lavado.',
                'precio' => 1299.00,
                'precio_oferta' => 1199.00,
                'stock' => 30,
                'sku' => 'IND-LRI16DTN-001',
                'codigo_barras' => '884116987654',
                'imagen_principal' => 'assets/productos/LAVADORA-INDURAMA-LAVADORA-AUTOMATICA-LRI-16DTN.jpg',
                'destacado' => false,
                'activo' => true,
                'categoria_id' => $lavadoras->id,
                'marca' => 'Indurama',
                'modelo' => 'LRI-16DTN',
                'garantia' => '2 años',
                'meta_title' => 'Lavadora Indurama LRI-16DTN 16KG - Control digital',
                'meta_description' => 'Lavadora Indurama 16 kg con control digital y programas inteligentes',
                'atributos_extra' => json_encode([
                    'capacidad' => '16 kg',
                    'tipo' => 'Carga superior',
                    'control' => 'Digital',
                    'ahorro' => 'Agua y energía',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Lavadora Indurama Automática LRI-18DGR 18 KG',
                'slug' => 'lavadora-indurama-automatica-lri-18dgr-18kg',
                'descripcion' => 'Lavadora Indurama automática de 18 kg de gran capacidad, ideal para familias numerosas.',
                'precio' => 1499.00,
                'precio_oferta' => 1349.00,
                'stock' => 25,
                'sku' => 'IND-LRI18DGR-001',
                'codigo_barras' => '884116987655',
                'imagen_principal' => 'assets/productos/LAVADORA-INDURAMA-LAVADORA-AUTOMATICA-LRI-18DGR.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $lavadoras->id,
                'marca' => 'Indurama',
                'modelo' => 'LRI-18DGR',
                'garantia' => '2 años',
                'meta_title' => 'Lavadora Indurama LRI-18DGR 18KG - Gran capacidad',
                'meta_description' => 'Lavadora Indurama 18 kg para familias numerosas con eficiencia avanzada',
                'atributos_extra' => json_encode([
                    'capacidad' => '18 kg',
                    'tipo' => 'Carga superior',
                    'programas' => '12 programas de lavado',
                    'ideal_para' => 'Familias numerosas',
                ]),
            ]);

            // Lavadoras Indurama Serie Grande
            Producto::create([
                'nombre' => 'Lavadora Indurama 19 KG LRI-19CRI',
                'slug' => 'lavadora-indurama-19kg-lri-19cri',
                'descripcion' => 'Lavadora Indurama automática de 19 kg de capacidad, perfecta para hogares grandes con máxima eficiencia.',
                'precio' => 1599.00,
                'precio_oferta' => 1399.00,
                'stock' => 22,
                'sku' => 'IND-LRI19CRI-001',
                'codigo_barras' => '884116987656',
                'imagen_principal' => 'assets/productos/LAVADORA-INDURAMA-LAVADORA-19-KG-LRI-19CRI.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $lavadoras->id,
                'marca' => 'Indurama',
                'modelo' => 'LRI-19CRI',
                'garantia' => '2 años',
                'meta_title' => 'Lavadora Indurama 19 KG LRI-19CRI - Máxima capacidad',
                'meta_description' => 'Lavadora Indurama LRI-19CRI de 19 kg para familias grandes',
                'atributos_extra' => json_encode([
                    'capacidad' => '19 kg',
                    'tipo' => 'Carga superior',
                    'programas' => '12 programas de lavado',
                    'eficiencia' => 'Máxima eficiencia',
                ]),
            ]);

            Producto::create([
                'nombre' => 'Lavadora Indurama 21 KG LRI-21CRI',
                'slug' => 'lavadora-indurama-21kg-lri-21cri',
                'descripcion' => 'Lavadora Indurama automática de 21 kg, la de mayor capacidad para uso doméstico e institucional.',
                'precio' => 1799.00,
                'precio_oferta' => 1599.00,
                'stock' => 18,
                'sku' => 'IND-LRI21CRI-001',
                'codigo_barras' => '884116987657',
                'imagen_principal' => 'assets/productos/LAVADORA-INDURAMA-LAVADORA-21-KG-LRI-21CRI.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $lavadoras->id,
                'marca' => 'Indurama',
                'modelo' => 'LRI-21CRI',
                'garantia' => '2 años',
                'meta_title' => 'Lavadora Indurama 21 KG LRI-21CRI - Máxima capacidad',
                'meta_description' => 'Lavadora Indurama LRI-21CRI de 21 kg, ideal para uso doméstico e institucional',
                'atributos_extra' => json_encode([
                    'capacidad' => '21 kg',
                    'tipo' => 'Carga superior',
                    'programas' => '15 programas de lavado',
                    'uso' => 'Doméstico e institucional',
                ]),
            ]);

            // Lavadoras LG
            Producto::create([
                'nombre' => 'Lavadora LG WT19WVT8 19 KG Blanco',
                'slug' => 'lavadora-lg-wt19wvt8-19kg-blanco',
                'descripcion' => 'Lavadora LG de 19 kg en color blanco con tecnología avanzada y múltiples programas inteligentes.',
                'precio' => 1899.00,
                'precio_oferta' => 1699.00,
                'stock' => 20,
                'sku' => 'LG-WT19WVT8-001',
                'codigo_barras' => '884116987658',
                'imagen_principal' => 'assets/productos/LAVADORA-Lavadora-Lg-WT19WVTB-19-Kg-BLANCA.jpg',
                'destacado' => true,
                'activo' => true,
                'categoria_id' => $lavadoras->id,
                'marca' => 'LG',
                'modelo' => 'WT19WVT8',
                'garantia' => '2 años',
                'meta_title' => 'Lavadora LG WT19WVT8 19KG - Tecnología inteligente',
                'meta_description' => 'Lavadora LG 19 kg con tecnología avanzada y programas inteligentes',
                'atributos_extra' => json_encode([
                    'capacidad' => '19 kg',
                    'tipo' => 'Carga superior',
                    'color' => 'Blanco',
                    'tecnologia' => 'Inteligente',
                    'programas' => 'Múltiples programas',
                ]),
            ]);
        }
    }
} 